services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      target: development
      args:
        PYTHON_VERSION: 3.12
        NODEJS_VERSION: latest
    volumes:
      - ./:/workspace
      - uv-cache:/home/vscode/.cache/uv
      - claude-data:/home/vscode/.claude
      - gemini-data:/home/vscode/.gemini
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    working_dir: /workspace
    command: tail -f /dev/null
    user: vscode

volumes:
  uv-cache:
  claude-data:
  gemini-data:
